apiVersion: v1
kind: Pod
metadata:
    name: my-database
spec:
    containers:
      - name: database
        image: mysql:5.7
        env:
            # _
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: data
    volumes:
      - name: data
        persistentVolumeClaim:
            claimName: my-volume-claim
