apiVersion: v1
kind: PersistentVolume
metadata:
    name: my-volume
spec:
    capacity:
        storage: 10Gi
    accessModes:
      - ReadWriteOnce
        #awsElasticBlockStore:
        #volumeID: vol-xxxx
        #fstype: ext4
    hostPath:
        path: /data/my-volume
