apiVersion: v1
kind: Pod
metadata:
    name: my-pod-with-secret
spec:
    containers:
      - name: my-pod-with-secret
        image: nginx
        volumeMounts:
          - name: secret
            mountPath: /et/secret
    volumes:
      - name: secret
        secret:
            name: my-secret
