apiVersion: v1
kind: Pod
metadata:
    name: my-pod-with-configmap
spec:
    containers:
      - name: my-service-with-config
        image: nginx
        env:
          - name: SOME_VALUE
            valueFrom:
                configMapKeyRef:
                    name: my-configmap
                    key: someVariable
