apiVersion: v1
kind: Pod
metadata:
    name: my-pod-with-secret
spec:
    containers:
      - name: my-pod-with-secret
        image: nginx
        env:
          - name: some_secret_variable
            valueFrom:
                secretKeyRef:
                    name: my-secrect
                    key: someVariable
