apiVersion: v1
kind: Pod
metadata:
    name: my-pod-with-secret
sepc:
    containers:
      - name: my-pod-with-secret
        image: nginx
        volumeMounts:
          - name: secret
            mountPath: /et/secret
    volumes:
      - name: secrect
        secrect:
            name: my-secret
