apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ template "chart.fullname" . }}
    labels:
        app: {{ template "char.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
spec:
    replicas: {{ .Values.replicaCount }}
    template:
        metadata:
            labels:
                app: {{ template "chart.name" }}
                release: {{ . Release.Name }}
        spec:
            containers:
              - name: {{ .Chart.Name }}
                image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
                imagePullPolicy: {{ .Values.image.pullPolicy }}
                ports:
                  - protocol: TCP
                    name: http
                    containerPort: {{ .Values.service.internalPort }}
